name: example
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  stacked: ^3.4.0
  stacked_services: ^1.1.0
  retrofit: ^4.2.0
  dio: ^5.5.0+1
  json_annotation: ^4.8.1
  motocode_core:
    path: ../
  stacked_shared: ^1.4.1

dev_dependencies:
  build_runner: ^2.4.12
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  mockito: ^5.4.1
  stacked_generator: ^1.3.3
  retrofit_generator: ^8.2.0
  json_serializable: ^6.6.2

flutter:
  uses-material-design: true
